; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed_xiao_rp2350]
platform = https://github.com/maxgerhardt/platform-raspberrypi
board = seeed_xiao_rp2350
framework = arduino
lib_deps = 
	khoih-prog/RP2040_PWM@^1.7.0
	br3ttb/PID@^1.2.1
	eyr1n/RP2040PIO_CAN@^0.0.6
	https://github.com/adafruit/Adafruit_VL6180X.git
