#!/bin/bash
[ -z "$HEX_NON_REALTIME" ] && [ -f /etc/profile.d/hexapod_env.sh ] && source /etc/profile.d/hexapod_env.sh 

cd "$HEX_NON_REALTIME/container" || { echo "Cannot cd to $HEX_NON_REALTIME/container"; exit 1; }
docker compose -f docker-compose-prod.yml up -d

