services:
  Hexapod:
    image: hexapod:latest
    container_name: hexapod_latest
    volumes:
      - ./src:/app/src
      - /var/run/dbus/:/var/run/dbus/:z
      - /dev/ttyAMA0:/dev/ttyAMA0:rw
      - /dev/input/:/dev/input/
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ${XAUTH_FILE}:/root/.Xauthority
    environment:
      - DISPLAY=:0
      - XAUTHORITY=/root/.Xauthority
      - QT_QPA_PLATFORM=xcb
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    entrypoint: ["bash", "/app/src/idle_entry_point.sh"]
