services:
  Hexapod:
    image: hexapod:latest
    container_name: hexapod_latest
    network_mode: host
    volumes:
      - ./src:/app/src
      - /var/run/dbus/:/var/run/dbus/:z
      - /dev/ttyAMA0:/dev/ttyAMA0:rw
      - /dev/input/:/dev/input/
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ${XAUTH_FILE}:/root/.Xauthority:ro
    environment:
      - DISPLAY=${DISPLAY:-:0}
      - XAUTHORITY=/root/.Xauthority
      - QT_QPA_PLATFORM=xcb
      - XDG_RUNTIME_DIR=/tmp
      - WAYLAND_DISPLAY=${WAYLAND_DISPLAY}
      - SDL_VIDEODRIVER=x11
      - SDL_VIDEO_X11_FORCE_EGL=1
      - LIBGL_ALWAYS_INDIRECT=1
    devices:
      - /dev/dri:/dev/dri
    privileged: true
    entrypoint: ["bash", "/app/src/entry_point.sh"]
   # restart: unless-stopped